import {norm,number,clean,joinRows,filterRows,totals,groups,sortRows,metric,csv,parseCredit,ROLES} from './core.js?v=20260910-3';
import * as Sync from './sync.js?v=20260910-3';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const colors=['#33bdb8','#607cf0','#edaa4b','#d66ab7','#64a5db','#91bf65','#ee6570','#9383d5','#48a881','#b28c61'];
const labels={extra:'Extra amount',bank:'Payment-channel extra amount',sales:'POS & MFS sales',projection:'Month-end projection',target:'Target',saving:'Save amount',incentive:'Incentive',code:'Outlet code',name:'Outlet name',leader:'RHO / Leader',zonal:'Zonal',format:'Format',division:'Division',district:'District',area:'Area',location:'Location type',status:'Outlet status',serial:'Serial',other:'Additional column'};
const mappingLabels={matched:'Matched',manual:'Manual',unmatched:'Not found',unverified:'Unverified',conflict:'Duplicate match',incomplete:'Incomplete'};
const REFERENCE_PUBLISHED_AT='2026-09-08T17:14:25+06:00';
const state={payload:null,rows:[],filtered:[],filters:{},banks:[],search:'',unit:'lac',tab:'overview',group:'leader',sort:'extra',direction:'desc',page:1,pageSize:50,visible:null,mappingPage:1,mappingSearch:'',mappingShow:'issues',dirty:false,busy:false,baseCloudTime:null,zoneTime:null,lastCloudTime:null,leaderSort:'extra',leaderDirection:'desc',mappingSort:'extra-desc',knownColumns:new Set(),cloudError:false,cloudFailures:0,ruleDraft:{},activeRules:{},pausedByConflict:false};
const worker=new URL(location.href).searchParams.get('snapshot-worker')==='1';
if(worker)document.documentElement.classList.add('worker-mode');
let toastTimer,pollBusy=false,autoBusy=false,refreshAt=0;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,7000);}
function banner(message){$('status-banner').textContent=message;$('status-banner').hidden=!message;}
function time(value){if(!value)return 'Not published yet';const d=new Date(value);return Number.isNaN(d.getTime())?'Not available':d.toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'Asia/Dhaka'});}
function snapshotTime(payload){return payload?.generatedAt||(payload?.credit?.meta?.reference?REFERENCE_PUBLISHED_AT:null);}
const nf=new Intl.NumberFormat('en-US',{maximumFractionDigits:2,minimumFractionDigits:2});
const count=n=>new Intl.NumberFormat('en-US').format(n??0);
const pct=n=>Number.isFinite(n)?`${(n*100).toFixed(1)}%`:'—';
function money(n,unit=state.unit,suffix=true){if(n==null||!Number.isFinite(n))return '—';const div=unit==='lac'?100000:unit==='cr'?10000000:1;return nf.format(n/div)+(suffix?(unit==='lac'?' Lakh':unit==='cr'?' Cr':''):'');}
function exact(n){return n==null?'Unavailable':`৳${nf.format(n)}`;}
function kpiMoney(n){if(n==null)return '—';return `${money(n,state.unit,false)}<small>${state.unit==='lac'?'Lakh':state.unit==='cr'?'Cr':'BDT'}</small>`;}
const storePreference=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));}catch{}};
const getPreference=(k,f)=>{try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
function columns(){
  if(!state.payload)return [];
  return [{key:'code',label:'Outlet code'},{key:'name',label:'Outlet name'},{key:'leader',label:'RHO / Leader'},{key:'zonal',label:'Zonal'},{key:'extra',label:state.banks.length?'Selected bank extra':'Extra amount',numeric:true},{key:'projection',label:'Projection',numeric:true},{key:'target',label:'Target',numeric:true},{key:'saving',label:'Save amount',numeric:true},{key:'incentive',label:'Incentive',numeric:true},{key:'sales',label:'POS & MFS sales',numeric:true},...state.payload.credit.banks.map(b=>({key:'bank:'+b.key,label:b.label,numeric:true})),...['format','division','district','location','mapping'].map(key=>({key,label:key==='mapping'?'Mapping':key[0].toUpperCase()+key.slice(1)})),...state.payload.credit.columns.filter(c=>c.role==='other').map(c=>({key:'raw:'+c.key,label:c.label,numeric:c.numeric}))];
}
function visibleColumns(){const cols=columns();return cols.filter(c=>state.visible?.has(c.key));}
function cell(r,c){let v=metric(r,c.key,state.banks);if(state.banks.length&&['projection','target','saving','incentive'].includes(c.key))v=null;if(c.key==='mapping')return `<span class="status-tag ${esc(r.mapping)}">${mappingLabels[r.mapping]}</span>`;return c.numeric?money(number(v),'bdt',false):esc(v||'—');}
function renderTable(rows,cols,{sortable=false,total=true}={}){
  if(!rows.length)return '<div class="empty">No outlets match this view. Adjust or reset the filters.</div>';
  const head=cols.map(c=>`<th class="${c.numeric?'num':''}" ${sortable&&c.key===state.sort?`aria-sort="${state.direction==='asc'?'ascending':'descending'}"`:''}>${sortable?`<button data-sort="${esc(c.key)}">${esc(c.label)} ${c.key===state.sort?(state.direction==='asc'?'↑':'↓'):'↕'}</button>`:esc(c.label)}</th>`).join('');
  const body=rows.map(r=>`<tr>${cols.map(c=>`<td class="${c.numeric?'num':''}" title="${esc(metric(r,c.key,state.banks)??'')}">${cell(r,c)}</td>`).join('')}</tr>`).join('');
  const foot=total?`<tfoot><tr>${cols.map((c,i)=>`<td class="${c.numeric?'num':''}">${i===0?'VIEW TOTAL':c.numeric?sumColumn(state.filtered,c):''}</td>`).join('')}</tr></tfoot>`:'';
  return `<table><thead><tr>${head}</tr></thead><tbody>${body}</tbody>${foot}</table>`;
}
function sumColumn(rows,c){if(state.banks.length&&['projection','target','saving','incentive'].includes(c.key))return '—';if(c.key.startsWith('raw:'))return '';const vals=rows.map(r=>number(metric(r,c.key,state.banks))).filter(v=>v!==null);return vals.length?money(vals.reduce((s,v)=>s+v,0),'bdt',false):'—';}
function refreshRows(){if(!state.payload)return;state.rows=joinRows(state.payload.credit,state.payload.zone,state.payload.overrides);state.filtered=filterRows(state.rows,state.filters,state.search,state.banks);}
const filterSpecs=[['leader','RHO / Leader'],['zonal','Zonal'],['format','Format'],['district','District'],['division','Division'],['location','Location type'],['bank','Payment channel'],['mapping','Mapping']];
function filterList(k){
  if(k==='bank')return state.payload.credit.banks.map(b=>({value:b.key,label:b.label,count:state.rows.filter(r=>!r.excluded&&(r.bankValues[b.key]??0)!==0).length}));
  const other={...state.filters};delete other[k];const eligible=filterRows(state.rows,other,state.search,state.banks);const map=new Map();eligible.forEach(r=>map.set(r[k],(map.get(r[k])||0)+1));
  for(const v of state.filters[k]||[])if(!map.has(v))map.set(v,0);
  return [...map].sort(([a],[b])=>String(a).localeCompare(String(b))).map(([value,count])=>({value,label:k==='mapping'?mappingLabels[value]:value,count}));
}
function renderFilters(){
  const open=[...document.querySelectorAll('[data-filter-box][open]')].map(x=>x.dataset.filterBox);
  $('filters').innerHTML=filterSpecs.map(([k,label])=>{const selected=k==='bank'?state.banks:state.filters[k]||[];const opts=filterList(k);return `<div class="filter-group"><span class="filter-label">${label}</span><details data-filter-box="${k}" ${open.includes(k)?'open':''}><summary>${selected.length?esc(selected.length===1?(opts.find(o=>o.value===selected[0])?.label||selected[0]):selected.length+' selected'):'All '+(k==='bank'?'channels':k==='mapping'?'statuses':label==='RHO / Leader'?'leaders':label.toLowerCase())}</summary><div class="filter-popover"><input type="search" placeholder="Find ${label.toLowerCase()}" data-option-search="${k}" aria-label="Search ${label} options"><button class="text-button" data-clear-filter="${k}">Clear selection</button><div class="filter-options">${opts.map(o=>`<label data-option-label="${esc(String(o.label).toLowerCase())}"><input type="checkbox" data-filter="${k}" value="${esc(o.value)}" ${selected.includes(o.value)?'checked':''}><span>${esc(o.label)}</span><small>${count(o.count)}</small></label>`).join('')||'<span class="muted">No matching options</span>'}</div></div></details></div>`;}).join('');
  $('active-filters').innerHTML=[...Object.entries(state.filters).flatMap(([k,vals])=>vals.map(v=>`<button class="chip" data-remove-filter="${k}" data-value="${esc(v)}">${esc(k==='mapping'?mappingLabels[v]:v)} ×</button>`)),...state.banks.map(v=>`<button class="chip" data-remove-filter="bank" data-value="${esc(v)}">${esc(v)} ×</button>`)].join('');
}
function renderOverview(){
  const rows=state.filtered,t=totals(rows,state.banks);const all=totals(state.rows);const excluded=state.rows.filter(r=>r.excluded);
  $('scope').textContent=`${count(t.outlets)} outlets · ${count(rows.length)} source rows${excluded.length?' · '+count(excluded.length)+' excluded':''}`;
  const bankMode=Boolean(state.banks.length);
  const metrics=[{label:bankMode?'Selected channel extra':'Total extra amount',value:t.extra,foot:`${pct((t.extra??0)/(all.extra||0))} of unfiltered source`,focus:true},{label:'Month-end projection',value:bankMode?null:t.projection,foot:bankMode?'Not split by payment channel':`${count(t.projectionCoverage)} of ${count(rows.length)} rows available`},{label:'Allocated target',value:bankMode?null:t.target,foot:bankMode?'Not split by payment channel':`${count(t.targetCoverage)}/${count(rows.length)} rows · Source target ${money(state.payload.credit.meta.targetTotal)}`},{label:'Save amount',value:bankMode?null:t.saving,foot:bankMode?'Not split by payment channel':`${count(t.savingCoverage)} of ${count(rows.length)} rows available`,sign:true},{label:'Charged outlets',text:count(t.charged),foot:`${pct(t.charged/(t.outlets||1))} with positive extra amount`},{label:'Mapping verified',text:pct(t.mapped/(rows.length||1)),foot:`${count(t.mapped)} of ${count(rows.length)} rows confirmed`}];
  $('kpis').innerHTML=metrics.map(m=>`<article class="kpi ${m.focus?'focus':''}"><div class="kpi-label">${m.label}</div><div class="kpi-value ${m.sign&&m.value<0?'negative':''}" title="${m.value!=null?exact(m.value):''}">${m.text??kpiMoney(m.value)}</div><div class="kpi-foot">${esc(m.foot)}</div></article>`).join('');
  const top=sortRows(rows,'extra','desc',state.banks).slice(0,10);const topSum=totals(top,state.banks).extra??0;const gs=groups(rows,'leader',state.banks);
  $('insight').innerHTML=rows.length?`The top <b>${top.length} outlet records</b> account for <b>${pct(topSum/(t.extra||1))}</b> of extra amount. ${gs[0]?`<b>${esc(gs[0].name)}</b> has the highest leader total at <b>৳${money(gs[0].extra)}</b>.`:''}${excluded.length?` Excluded amount: <b>${exact(totals(excluded).extra)}</b>.`:''}`:'No data matches the selected filters.';
  renderCharts();
  const topcols=[{key:'code',label:'Code'},{key:'name',label:'Outlet name'},{key:'leader',label:'RHO / Leader'},{key:'zonal',label:'Zonal'},{key:'extra',label:bankMode?'Selected channel extra':'Extra amount',numeric:true},{key:'projection',label:'Month End Projection',numeric:true},{key:'mapping',label:'Mapping'}];
  $('top-outlets').innerHTML=renderTable(top.slice(0,6),topcols,{total:false});
  renderLeaderTable();
}
function renderCharts(){
  const banks=state.payload.credit.banks.filter(b=>!state.banks.length||state.banks.includes(b.key));const gs=groups(state.filtered,state.group,state.banks);const max=Math.max(...gs.map(g=>Math.abs(g.extra||0)),1);const limit=$('chart-limit').value;const shown=limit==='all'?gs:gs.slice(0,Number(limit));
  $('chart-title').textContent='Extra amount by '+(state.group==='leader'?'RHO / Leader':'Zonal');
  $('chart-subtitle').textContent=`${shown.length} of ${gs.length} ${state.group==='leader'?'leaders':'zonals'} · highest first`;
  $('leader-chart').innerHTML=shown.length?shown.map(g=>{
    const vals=banks.map(b=>({b,value:g.rows.reduce((s,r)=>s+(r.bankValues[b.key]??0),0)}));const positive=vals.every(x=>x.value>=0);const sum=vals.reduce((s,x)=>s+x.value,0);const differs=Math.abs(sum-(g.extra??0))>.02;
    const segments=positive&&sum>0&&!differs?vals.map(({b,value})=>`<span class="bar-segment" style="width:${value/sum*100}%;background:${bankColor(b.key)}" title="${esc(b.label)}: ${exact(value)}"></span>`).join(''):`<span class="bar-segment" style="width:100%;background:${(g.extra??0)<0?'var(--accent)':'var(--teal)'}"></span>`;
    return `<div class="bar-row"><button class="bar-name" data-drill="${esc(g.name)}" title="Filter ${esc(g.name)}">${esc(g.name)}</button><div class="bar-track" role="img" aria-label="${esc(g.name)}: ${exact(g.extra)}"><div class="bar-fill" style="width:${Math.abs(g.extra??0)/max*100}%">${segments}</div></div><span class="bar-value" title="${exact(g.extra)}">${money(g.extra)}</span></div>`;
  }).join(''):'<div class="empty">No leadership data in this view.</div>';
  $('bank-legend').innerHTML=banks.map(b=>`<span><i class="swatch" style="background:${bankColor(b.key)}"></i>${esc(b.label)}</span>`).join('');
  const channels=banks.map(b=>({...b,amount:state.filtered.reduce((s,r)=>s+(r.bankValues[b.key]??0),0)})).sort((a,b)=>b.amount-a.amount);const total=channels.reduce((s,b)=>s+b.amount,0);const positive=channels.every(b=>b.amount>=0);let p=0;
  const gradient=channels.filter(b=>b.amount>0).map(b=>{const start=p;p+=b.amount/(total||1)*100;return `${bankColor(b.key)} ${start}% ${p}%`;}).join(',');
  const leading=channels[0];
  $('channel-chart').innerHTML=total>0&&positive?`<div class="donut-area"><div class="donut" role="img" aria-label="Channel contributions totaling ${exact(total)}" style="background:conic-gradient(${gradient})"><div class="donut-label">${channels.filter(b=>b.amount!==0).length}<small>active channels</small></div></div><div class="donut-note">Largest contribution<b>${pct((leading?.amount??0)/total)}</b>${esc(leading?.label)} · ${money(leading?.amount)}</div></div>`:'<div class="empty">'+(positive?'No channel charges in this view.':'Negative adjustments are shown in the channel table.')+'</div>';
  $('channel-bars').innerHTML=channels.map(b=>`<div class="channel-row"><i class="swatch" style="background:${bankColor(b.key)}"></i><button data-bank-drill="${esc(b.key)}">${esc(b.label)}</button><span class="channel-number" title="${exact(b.amount)}">${money(b.amount,state.unit,false)}</span><small>${total?pct(b.amount/total):'—'}</small></div>`).join('');
}
function bankColor(key){return colors[state.payload.credit.banks.findIndex(b=>b.key===key)%colors.length]||colors[0];}
function leaderSummary(){const banks=state.payload.credit.banks.filter(b=>!state.banks.length||state.banks.includes(b.key));const gs=groups(state.filtered,'leader',state.banks);const val=g=>state.leaderSort.startsWith('bank:')?g.rows.reduce((s,r)=>s+(r.bankValues[state.leaderSort.slice(5)]??0),0):state.leaderSort==='name'?g.name:g[state.leaderSort];gs.sort((a,b)=>{const x=val(a),y=val(b);return (state.leaderDirection==='asc'?1:-1)*(typeof x==='number'?x-y:String(x).localeCompare(String(y)));});return {banks,gs};}
function renderLeaderTable(){const {banks,gs}=leaderSummary();$('leader-table').innerHTML=gs.length?`<table><thead><tr><th><button data-leader-sort="name">RHO / Leader ↕</button></th><th class="num"><button data-leader-sort="outlets">Outlets ↕</button></th>${banks.map(b=>`<th class="num"><button data-leader-sort="bank:${esc(b.key)}">${esc(b.label)} ↕</button></th>`).join('')}<th class="num"><button data-leader-sort="extra">Total extra amount ↕</button></th><th class="num"><button data-leader-sort="projection">Month End Projection ↕</button></th><th class="num"><button data-leader-sort="extra">Share ↕</button></th></tr></thead><tbody>${gs.map(g=>`<tr><td>${esc(g.name)}</td><td class="num">${count(g.outlets)}</td>${banks.map(b=>`<td class="num">${money(g.rows.reduce((s,r)=>s+(r.bankValues[b.key]??0),0),'bdt',false)}</td>`).join('')}<td class="num"><b>${money(g.extra,'bdt',false)}</b></td><td class="num">${money(g.projection,'bdt',false)}</td><td class="num">${pct((g.extra??0)/(totals(state.filtered,state.banks).extra||1))}</td></tr>`).join('')}</tbody><tfoot><tr><td>VIEW TOTAL</td><td class="num">${count(totals(state.filtered).outlets)}</td>${banks.map(b=>`<td class="num">${money(state.filtered.reduce((s,r)=>s+(r.bankValues[b.key]??0),0),'bdt',false)}</td>`).join('')}<td class="num">${money(totals(state.filtered,state.banks).extra,'bdt',false)}</td><td class="num">${money(totals(state.filtered,state.banks).projection,'bdt',false)}</td><td class="num">100%</td></tr></tfoot></table>`:'<div class="empty">No leader totals available.</div>';}
function renderOutlets(){const cols=visibleColumns();const rows=sortRows(state.filtered,state.sort,state.direction,state.banks);const size=state.pageSize==='all'?Math.max(rows.length,1):Number(state.pageSize);const pages=Math.max(1,Math.ceil(rows.length/size));state.page=Math.min(state.page,pages);const start=(state.page-1)*size;
  $('outlet-title').textContent=`${count(rows.length)} outlet records`;$('outlet-table').innerHTML=renderTable(rows.slice(start,start+size),cols,{sortable:true});$('table-summary').textContent=rows.length?`${count(start+1)}–${count(Math.min(rows.length,start+size))} of ${count(rows.length)} · amounts in BDT`:'No matching rows';$('page-number').textContent=`${state.page} / ${pages}`;$('prev').disabled=state.page<=1;$('next').disabled=state.page>=pages;
  $('column-options').innerHTML=columns().map(c=>`<label><input type="checkbox" data-column="${esc(c.key)}" ${state.visible.has(c.key)?'checked':''} ${c.key==='code'?'disabled':''}>${esc(c.label)}</label>`).join('');
}
function mappingRows(){return state.rows.filter(r=>{if(state.mappingShow==='issues'&&['matched','manual'].includes(r.mapping))return false;if(state.mappingShow==='manual'&&r.mapping!=='manual')return false;if(state.mappingShow==='excluded'&&!r.excluded)return false;const q=state.mappingSearch.toLowerCase();return !q||[r.code,r.name,r.leader,r.zonal].join(' ').toLowerCase().includes(q);}).sort((a,b)=>state.mappingSort==='code'?a.code.localeCompare(b.code):state.mappingSort==='leader'?a.leader.localeCompare(b.leader):state.mappingSort==='mapping'?a.mapping.localeCompare(b.mapping):(state.mappingSort==='extra-asc'?1:-1)*((a.extra??0)-(b.extra??0)));}
function renderMapping(){
  const issues=state.rows.filter(r=>!['matched','manual'].includes(r.mapping));const excluded=state.rows.filter(r=>r.excluded);const list=mappingRows();const pages=Math.max(1,Math.ceil(list.length/50));state.mappingPage=Math.min(state.mappingPage,pages);
  $('mapping-description').textContent=state.payload.zone?'Outlet codes are matched to the current Zone Distribution source. Enter both Zonal and RHO to resolve an exception. Exclusions remove the outlet from all totals and charts. Changes apply to all rows with the same outlet code.':'The current Zone Distribution file has not been loaded. Existing workbook leadership is shown provisionally. Load the Zone file to identify genuinely missing outlets. You can still make a manual assignment.';
  $('mapping-summary').textContent=`${count(issues.length)} rows need attention · ${count(excluded.length)} excluded (${exact(totals(excluded).extra)})${state.dirty?' · Draft changes on this browser; publish to share.':''}`;
  $('exclude-unmatched').disabled=!state.payload.zone;$('restore-excluded').disabled=!excluded.length;
  const shown=list.slice((state.mappingPage-1)*50,state.mappingPage*50);
  $('mapping-table').innerHTML=shown.length?`<table><thead><tr><th>Outlet</th><th>Match status</th><th class="num">Extra amount</th><th>RHO / Leader</th><th>Zonal</th><th>Action</th></tr></thead><tbody>${shown.map(r=>`<tr class="mapping-row ${r.excluded?'excluded':''}" data-map-row="${esc(r.uid)}"><td class="outlet-cell"><b>${esc(r.code||'Missing code')}</b><small>${esc(r.name)}</small></td><td><span class="status-tag ${r.mapping}">${mappingLabels[r.mapping]}</span>${r.excluded?' <span class="status-tag">Excluded</span>':''}</td><td class="num">${money(r.extra,'bdt',false)}</td><td><input class="mapping-table-input" data-map-field="leader" list="leader-names" value="${esc(r.leader==='Unassigned'?'':r.leader)}" aria-label="RHO for ${esc(r.code||r.id)}" placeholder="RHO / Leader"></td><td><input class="mapping-table-input" data-map-field="zonal" list="zonal-names" value="${esc(r.zonal==='Unassigned'?'':r.zonal)}" aria-label="Zonal for ${esc(r.code||r.id)}" placeholder="Zonal"></td><td><button class="button small" data-save-map="${esc(r.uid)}">Save</button> <button class="button small" data-exclude="${esc(r.uid)}">${r.excluded?'Restore':'Exclude'}</button>${Object.keys(r.manual).length?` <button class="text-button" data-revert-map="${esc(r.uid)}">Reset</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">No outlets in this mapping view.</div>';
  $('mapping-page-summary').textContent=`${count(list.length)} records · page ${state.mappingPage} of ${pages}`;$('mapping-prev').disabled=state.mappingPage<=1;$('mapping-next').disabled=state.mappingPage>=pages;
  for(const [id,key] of [['leader-names','leader'],['zonal-names','zonal']])$(id).innerHTML=[...new Set(state.rows.map(r=>r[key]).filter(v=>v&&v!=='Unassigned'))].sort().map(v=>`<option value="${esc(v)}">`).join('');
}
function renderData(){
  const p=state.payload,c=p.credit,z=p.zone;
  const sourceItem=(name,meta,n)=>`<div class="source-detail"><span>${name}</span><div>${esc(meta?.fileName||'Not loaded')}<small>${meta?.sheetName?esc(meta.sheetName)+' · ':''}${count(n)} records${meta?.modifiedTime?' · updated '+time(meta.modifiedTime):''}</small></div></div>`;
  $('source-details').innerHTML=sourceItem('Zone Distribution',z?.meta,z?.rows?.length||0)+`<div class="source-detail"><span>Snapshot</span><div>${esc(time(snapshotTime(p)))}<small>${state.dirty?'Draft changes are not shared.':p.sourceKind==='reference'?'Bundled snapshot included with the dashboard.':'Latest data loaded on this browser.'}</small></div></div><div class="source-detail"><span>Source total</span><div>${exact(totals(state.rows).extra)}<small>Before filters or exclusions</small></div></div>`;
  const warnings=[...c.warnings];const targetSum=totals(state.rows).target;if(c.meta.targetTotal!=null&&targetSum!=null&&Math.abs(c.meta.targetTotal-targetSum)>.01)warnings.push(`The source target is ${exact(c.meta.targetTotal)}, but populated outlet targets total ${exact(targetSum)}. Unallocated balance: ${exact(c.meta.targetTotal-targetSum)}. Missing targets are not filled automatically.`);if(!z)warnings.unshift('Current Zone Distribution is not loaded. Workbook leadership is unverified.');const blank=state.rows.filter(r=>!r.code);if(blank.length)warnings.push(`${blank.length} record${blank.length===1?' has':'s have'} a blank outlet code. Excluded from all totals and calculations automatically.`);
  $('validation-notes').innerHTML=warnings.map(w=>`<div class="validation-note">${esc(w)}</div>`).join('')||'<p class="muted">Source table validated. No amount or code warnings.</p>';
  const extras=Object.keys(state.ruleDraft).filter(k=>!c.columns.some(x=>x.key===k));
  const rules=[...c.columns,...extras.map(key=>({key,role:state.ruleDraft[key],numeric:false}))];
  $('schema-table').innerHTML=`<table><thead><tr><th>Source heading</th><th>Detected / selected role</th><th>Type</th></tr></thead><tbody>${rules.map(col=>`<tr><td>${esc(col.key)}</td><td><select class="schema-role" data-rule="${esc(col.key)}" aria-label="Role for ${esc(col.key)}">${ROLES.map(r=>`<option value="${r}" ${(state.ruleDraft[col.key]||col.role)===r?'selected':''}>${esc(labels[r])}</option>`).join('')}</select></td><td>${col.numeric?'Numeric':'Text / mixed'}</td></tr>`).join('')}</tbody></table>`;
  renderConnection();
}
function renderConnection(){
  const d=window.ShwapnoDrive.describe();$('drive-status').textContent=d.authorized?'Drive connected · configured source folder ready':d.configReady?'Saved Drive setup found · reconnect to read files':'Reuse your existing Zone Distribution Google connection settings below.';
  const s=Sync.getPublisherSession();$('publisher-state').textContent=s?`Publisher: ${s.user?.email||'signed in'}. ${state.dirty?'Draft changes need publication.':'Ready to publish changed data.'}`:'Viewer mode. Sign in with the existing snapshot publisher account to share changes.';
  const canAuto=Boolean(s&&d.authorized);$('auto-snapshot').disabled=!canAuto;$('publish').disabled=state.busy;$('read-drive').disabled=state.busy;
}
function render(){if(!state.payload)return;refreshRows();for(const c of columns()){if(c.key.startsWith('raw:')&&!state.knownColumns.has(c.key))state.visible?.add(c.key);state.knownColumns.add(c.key);}$('period').textContent=state.payload.credit.meta.period||'Reporting period not provided';$('snapshot-time').textContent=time(snapshotTime(state.payload));$('source-badge').textContent=state.dirty?'Local draft · not published':state.payload.sourceKind==='reference'?'Supplied workbook':state.cloudError?'Cached snapshot':'Published snapshot';const issues=state.rows.filter(r=>!r.excluded&&!['matched','manual'].includes(r.mapping)).length;$('mapping-count').textContent=count(issues);
  let note='';if(!state.payload.zone)note='Current Zone Distribution has not been loaded. RHO and Zonal from the supplied workbook are unverified.';else if(state.dirty)note='You are viewing a local draft. Publish the snapshot to share the source, mappings and exclusions with other viewers.';else if(state.cloudError)note='The cloud snapshot is unavailable. Showing the last valid data; its snapshot time is shown above.';else if(issues)note=`${count(issues)} source rows need mapping attention. They remain included as Unassigned until resolved or excluded.`;banner(note);
  renderFilters();renderOverview();renderOutlets();renderMapping();if(state.tab==='data')renderData();$('footer-status').textContent=`Credit Card · ${count(state.rows.length)} source rows`;
}
function tab(name){if(!state.payload)return toast('Loading the source data…');state.tab=name;for(const b of document.querySelectorAll('[data-tab]')){b.classList.toggle('active',b.dataset.tab===name);if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');}for(const n of ['overview','outlets','mapping','data'])$(n+'-view').hidden=n!==name;$('filter-panel').hidden=['data','mapping'].includes(name);if(name==='data')renderData();if(name==='mapping')renderMapping();}
async function cache(){await Sync.localPut('workspace',{payload:state.payload,dirty:state.dirty,baseCloudTime:state.baseCloudTime});}
async function draft(){state.dirty=true;state.payload.sourceKind='draft';try{await cache();}catch(e){toast(e.message);}render();}
async function applyPublished(p){state.payload=p;state.dirty=false;state.baseCloudTime=p.cloudUpdatedAt;state.lastCloudTime=p.cloudUpdatedAt;state.activeRules=p.schemaOverrides||{};state.ruleDraft={...state.activeRules};state.pausedByConflict=false;state.cloudError=false;await cache();render();}
function download(name,text,type='text/csv;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportOutlets(){const cols=visibleColumns();const rows=sortRows(state.filtered,state.sort,state.direction,state.banks);download('Credit-Card-Extra-Amount-filtered.csv',csv(cols.map(c=>c.label),rows.map(r=>cols.map(c=>state.banks.length&&['projection','target','saving','incentive'].includes(c.key)?'':metric(r,c.key,state.banks)))));}
async function doRefresh({force=false}={}){
  if(state.busy)return;state.busy=true;$('refresh').disabled=true;
  try{const results=await Promise.allSettled([Sync.readPublished(),Sync.readPublishedZone()]);const published=results[0].status==='fulfilled'?results[0].value:null;const zone=results[1].status==='fulfilled'?results[1].value:null;
    if(state.dirty&&!force){if(published&&published.cloudUpdatedAt!==state.baseCloudTime)toast('A newer shared snapshot is available. Your draft was kept. Export a backup, then choose Use published data.');else toast('Your local draft is still active. Publish it to share.');}
    else if(published)await applyPublished(published);
    if(zone&&(!state.payload.zone||Date.parse(zone.meta.savedAt||'')>Date.parse(state.payload.zone.meta.savedAt||state.payload.zone.meta.modifiedTime||''))){state.payload.zone=zone;state.zoneTime=zone.meta.savedAt;await cache();}
    state.cloudError=results.some(r=>r.status==='rejected');if(force&&published)toast('Published data restored.');else if(!published&&!state.cloudError)toast('No Credit Card cloud snapshot yet. The supplied workbook is available.');
  }catch(e){state.cloudError=true;toast(e.message);}finally{state.busy=false;$('refresh').disabled=false;render();}
}
async function readSource({silent=false}={}){const incoming=await Sync.readDrive(state.activeRules,msg=>{if(!silent)$('drive-status').textContent=msg;});const changed=incoming.credit.meta.signature!==state.payload.credit.meta.signature||incoming.zone.meta.signature!==state.payload.zone?.meta.signature;if(changed){state.payload={...state.payload,...incoming};await draft();}return changed;}
async function takeSnapshot(){if(state.busy)return;state.busy=true;renderConnection();try{if(window.ShwapnoDrive.cachedToken())await readSource();const result=await Sync.publish({...state.payload,schemaOverrides:state.activeRules},state.baseCloudTime);await applyPublished(result.payload);toast(result.published?'Snapshot published. All viewers can see these figures.':'No changes found. The existing snapshot is current.');}catch(e){toast(e.message);$('drive-status').textContent=e.message;}finally{state.busy=false;renderConnection();}}
async function poll(){
  if(pollBusy||state.busy||(!worker&&document.hidden)||!state.payload||document.activeElement?.matches('[data-map-field],[data-rule],#rule-header'))return;
  const delay=state.cloudFailures?Math.min(60000,1000*2**Math.min(state.cloudFailures,6)):1000;if(Date.now()-refreshAt<delay)return;refreshAt=Date.now();pollBusy=true;
  try{const times=await Sync.publishedTimes();const hadError=state.cloudError;state.cloudFailures=0;state.cloudError=false;if(hadError)render();
    if(times[Sync.SNAPSHOT_KEY]&&times[Sync.SNAPSHOT_KEY]!==state.lastCloudTime){
      if(!state.dirty){const p=await Sync.readPublished();if(p)await applyPublished(p);}else if(times[Sync.SNAPSHOT_KEY]!==state.baseCloudTime&&!state.pausedByConflict){state.pausedByConflict=true;toast('A newer cloud snapshot exists. Automatic publishing is paused to protect your draft.');}
    }
    if(times['zone-distribution']&&times['zone-distribution']!==state.zoneTime&&!state.busy){const z=await Sync.readPublishedZone();if(z){state.zoneTime=times['zone-distribution'];if(!state.payload.zone||Date.parse(z.meta.savedAt||'')>Date.parse(state.payload.zone.meta.savedAt||state.payload.zone.meta.modifiedTime||'')){state.payload.zone=z;await cache();render();}}}
  }catch{state.cloudFailures++;if(!state.cloudError){state.cloudError=true;render();}}finally{pollBusy=false;}
}
async function autoSnapshot(){
  if(autoBusy||state.busy||state.pausedByConflict||(!worker&&document.hidden)||!state.payload||document.activeElement?.matches('[data-map-field],[data-rule],#rule-header'))return;
  if(!getPreference('credit-card-auto-snapshot',false)||!Sync.getPublisherSession()||!window.ShwapnoDrive.cachedToken())return;
  if(worker&&!window.DashboardDriveOwner?.isOwner())return;
  autoBusy=true;
  try{
    const run=async()=>{state.busy=true;const changed=await readSource({silent:true});if(changed||state.dirty){const r=await Sync.publish({...state.payload,schemaOverrides:state.activeRules},state.baseCloudTime);await applyPublished(r.payload);}};
    if(navigator.locks)await navigator.locks.request('credit-card-snapshot-publisher',{ifAvailable:true},async lock=>{if(lock)await run();});else await run();
  }catch(e){$('drive-status').textContent=e.message;}finally{autoBusy=false;state.busy=false;}
}
function setTheme(){const dark=document.documentElement.dataset.theme==='dark';$('theme-toggle').setAttribute('aria-checked',String(dark));$('theme-label').textContent=dark?'Dark':'Light';}
$('theme-toggle').onclick=()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('credit-card-theme',next);}catch{}setTheme();};setTheme();
document.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b)return;
  if(state.busy&&(b.dataset.saveMap||b.dataset.exclude||b.dataset.revertMap))return toast('Wait for the current source update to finish.');
  if(b.dataset.tab)tab(b.dataset.tab);
  if(b.dataset.group){state.group=b.dataset.group;document.querySelectorAll('[data-group]').forEach(x=>x.classList.toggle('active',x===b));renderCharts();}
  if(b.dataset.leaderSort){state.leaderDirection=state.leaderSort===b.dataset.leaderSort?(state.leaderDirection==='asc'?'desc':'asc'):'desc';state.leaderSort=b.dataset.leaderSort;renderLeaderTable();}
  if(b.dataset.sort){state.direction=state.sort===b.dataset.sort?(state.direction==='asc'?'desc':'asc'):'desc';state.sort=b.dataset.sort;renderOutlets();}
  if(b.dataset.drill){state.filters[state.group]=[b.dataset.drill];state.page=1;render();}
  if(b.dataset.bankDrill){state.banks=[b.dataset.bankDrill];state.page=1;render();}
  if(b.dataset.clearFilter){const k=b.dataset.clearFilter;if(k==='bank')state.banks=[];else delete state.filters[k];render();}
  if(b.dataset.removeFilter){const k=b.dataset.removeFilter,v=b.dataset.value;if(k==='bank')state.banks=state.banks.filter(x=>x!==v);else state.filters[k]=(state.filters[k]||[]).filter(x=>x!==v);render();}
  if(b.dataset.saveMap){const r=state.rows.find(x=>x.uid===b.dataset.saveMap);const row=b.closest('tr');const leader=clean(row.querySelector('[data-map-field=leader]').value),zonal=clean(row.querySelector('[data-map-field=zonal]').value);if(!leader||!zonal)return toast('Enter both RHO / Leader and Zonal.');state.payload.overrides[r.id]={...r.manual,leader,zonal,updatedAt:new Date().toISOString()};await draft();toast(`Assignment saved for ${r.code||'this source record'}.`);}
  if(b.dataset.exclude){const r=state.rows.find(x=>x.uid===b.dataset.exclude);state.payload.overrides[r.id]={...r.manual,excluded:!r.excluded,updatedAt:new Date().toISOString()};await draft();}
  if(b.dataset.revertMap){const r=state.rows.find(x=>x.uid===b.dataset.revertMap);delete state.payload.overrides[r.id];await draft();toast('Source mapping and inclusion restored.');}
});
document.addEventListener('change',e=>{const el=e.target;
  if(el.dataset.filter){const k=el.dataset.filter;let values=k==='bank'?state.banks:state.filters[k]||[];values=el.checked?[...new Set([...values,el.value])]:values.filter(v=>v!==el.value);if(k==='bank')state.banks=values;else state.filters[k]=values;state.page=1;render();}
  if(el.dataset.column){if(el.checked)state.visible.add(el.dataset.column);else state.visible.delete(el.dataset.column);storePreference('credit-card-columns',[...state.visible]);renderOutlets();}
  if(el.dataset.rule)state.ruleDraft[el.dataset.rule]=el.value;
});
document.addEventListener('input',e=>{if(e.target.dataset.optionSearch)for(const label of e.target.closest('.filter-popover').querySelectorAll('[data-option-label]'))label.hidden=!label.dataset.optionLabel.includes(e.target.value.toLowerCase());});
document.addEventListener('click',e=>{document.querySelectorAll('[data-filter-box][open]').forEach(d=>{if(!d.contains(e.target))d.open=false;});});
$('search').oninput=e=>{state.search=e.target.value;state.page=1;render();};
$('reset').onclick=()=>{state.search='';$('search').value='';state.filters={};state.banks=[];state.page=1;render();};
$('unit').onchange=e=>{state.unit=e.target.value;storePreference('credit-card-unit',state.unit);renderOverview();};
$('chart-limit').onchange=renderCharts;
$('data-button').onclick=()=>tab('data');$('all-outlets').onclick=()=>tab('outlets');
$('prev').onclick=()=>{state.page--;renderOutlets();};$('next').onclick=()=>{state.page++;renderOutlets();};$('page-size').onchange=e=>{state.pageSize=e.target.value;state.page=1;renderOutlets();};
$('mapping-sort').onchange=e=>{state.mappingSort=e.target.value;state.mappingPage=1;renderMapping();};
$('mapping-show').onchange=e=>{state.mappingShow=e.target.value;state.mappingPage=1;renderMapping();};$('mapping-search').oninput=e=>{state.mappingSearch=e.target.value;state.mappingPage=1;renderMapping();};$('mapping-prev').onclick=()=>{state.mappingPage--;renderMapping();};$('mapping-next').onclick=()=>{state.mappingPage++;renderMapping();};
$('exclude-unmatched').onclick=async()=>{for(const r of state.rows.filter(r=>r.mapping==='unmatched'))state.payload.overrides[r.id]={...r.manual,excluded:true,updatedAt:new Date().toISOString()};await draft();toast('Unmatched outlets excluded. Use Restore excluded to undo.');};
$('restore-excluded').onclick=async()=>{for(const r of state.rows.filter(r=>r.excluded))state.payload.overrides[r.id]={...r.manual,excluded:false,updatedAt:new Date().toISOString()};await draft();toast('All excluded outlets restored.');};
$('export').onclick=exportOutlets;
$('leader-export').onclick=()=>{const {banks,gs}=leaderSummary();download('Credit-Card-Leader-Wise.csv',csv(['RHO / Leader','Outlets',...banks.map(b=>b.label),'Total extra amount','Month End Projection'],gs.map(g=>[g.name,g.outlets,...banks.map(b=>g.rows.reduce((s,r)=>s+(r.bankValues[b.key]??0),0)),g.extra,g.projection])));};
$('mapping-export').onclick=()=>download('Credit-Card-Mapping-Backup.json',JSON.stringify({format:'credit-card-mapping-v1',exportedAt:new Date().toISOString(),overrides:state.payload.overrides,schemaOverrides:state.activeRules},null,2),'application/json');
$('mapping-import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)throw new Error('Mapping backup is too large.');const p=JSON.parse(await file.text());if(p.format!=='credit-card-mapping-v1'||!p.overrides||typeof p.overrides!=='object'||Array.isArray(p.overrides))throw new Error('Choose a mapping backup exported from this dashboard.');const valid={};for(const [key,v] of Object.entries(p.overrides)){if(['__proto__','constructor','prototype'].includes(key)||!v||typeof v!=='object')continue;valid[key]={leader:clean(v.leader),zonal:clean(v.zonal),excluded:v.excluded===true,updatedAt:new Date().toISOString()};}state.payload.overrides={...state.payload.overrides,...valid};for(const [key,value] of Object.entries(p.schemaOverrides||{}))if(ROLES.includes(value)&&!['__proto__','constructor','prototype'].includes(key))state.ruleDraft[key]=value;await draft();toast('Mapping backup imported. Apply Column rules to use any imported header rules.');}catch(err){toast(err.message);}e.target.value='';};
$('refresh').onclick=()=>doRefresh();
$('connect-drive').onclick=async()=>{try{if(!window.ShwapnoDrive.configReady()){tab('data');$('drive-form').closest('details').open=true;return toast('Enter the same Google connection settings used by Zone Distribution.');}await window.ShwapnoDrive.requestToken();renderConnection();toast('Drive connected. Read latest files to load both sources.');}catch(e){toast(e.message);}};
$('drive-form').onsubmit=e=>{e.preventDefault();try{window.ShwapnoDrive.saveConfig({clientId:$('client-id').value,apiKey:$('api-key').value,appId:$('app-id').value});toast('Shared Google connection settings saved.');renderConnection();}catch(e){toast(e.message);}};
$('publisher-form').onsubmit=async e=>{e.preventDefault();try{await Sync.signInPublisher($('publisher-email').value,$('publisher-password').value);$('publisher-password').value='';toast('Publisher signed in.');renderConnection();}catch(err){toast(err.message);}};
$('publisher-signout').onclick=()=>{Sync.signOutPublisher();storePreference('credit-card-auto-snapshot',false);$('auto-snapshot').checked=false;renderConnection();toast('Publisher signed out on this browser.');};
$('auto-snapshot').onchange=e=>{storePreference('credit-card-auto-snapshot',e.target.checked);toast(e.target.checked?'Automatic snapshots enabled while this page or the portal is open.':'Automatic snapshots paused.');if(e.target.checked)autoSnapshot();};
$('read-drive').onclick=async()=>{if(state.busy)return;state.busy=true;renderConnection();try{const changed=await readSource();toast(changed?'Both source files validated. Review and publish the snapshot.':'Both source files are unchanged.');}catch(e){toast(e.message);$('drive-status').textContent=e.message;}finally{state.busy=false;renderConnection();}};
$('publish').onclick=takeSnapshot;
$('file-import').onchange=async e=>{if(!e.target.files.length)return;state.busy=true;try{const result=await Sync.importFiles([...e.target.files],state.activeRules);if(result.credit)state.payload.credit=result.credit;if(result.zone)state.payload.zone=result.zone;await draft();toast('Files imported. Review the data, then publish to share.');}catch(err){toast(err.message);}finally{state.busy=false;e.target.value='';}};
$('reset-local').onclick=async()=>{try{const p=await Sync.readPublished();if(!p)return toast('No Credit Card snapshot has been published. Your draft was retained.');await applyPublished(p);toast('Published data loaded. Local draft replaced.');}catch(e){toast(e.message);}};
$('rule-role').innerHTML=ROLES.map(r=>`<option value="${r}">${labels[r]}</option>`).join('');
$('add-rule').onclick=()=>{const key=$('rule-header').value.trim();if(!key)return toast('Enter a column heading.');state.ruleDraft[key]=$('rule-role').value;$('rule-header').value='';renderData();toast('Rule added. Apply column rules to activate it.');};
$('save-rules').onclick=async()=>{try{const c=state.payload.credit;const width=Math.max(...c.columns.map(x=>x.index))+1;const headers=Array(width).fill('');c.columns.forEach(x=>headers[x.index]=x.key);const rows=c.records.map(r=>{const row=Array(width).fill('');c.columns.forEach(x=>row[x.index]=r.raw[x.key]??'');return row;});const next=parseCredit([{name:c.meta.sheetName,grid:[...(c.preamble||[]),headers,...rows]}],c.meta,state.ruleDraft);if(next.records.length!==c.records.length)throw new Error('These column roles change the number of outlet records. Check the code and amount roles before applying.');next.records.forEach((r,i)=>{r.id=c.records[i].id;r.sourceRow=c.records[i].sourceRow;});state.payload.credit=next;state.activeRules={...state.ruleDraft};state.payload.schemaOverrides=state.activeRules;await draft();toast('Column rules applied and saved for future imports.');}catch(e){toast(e.message);}};
async function init(){try{
  const cached=await Sync.localGet('workspace');
  if(cached?.payload?.credit?.records?.length){state.payload=cached.payload;state.dirty=!!cached.dirty;state.baseCloudTime=cached.baseCloudTime;state.lastCloudTime=state.baseCloudTime;}else{const r=await fetch('./data/reference.json?v=20260910-3');if(!r.ok)throw new Error('Initial dataset is missing. Upload the complete data folder with the dashboard files.');state.payload=await r.json();}
  state.payload.overrides||={};state.activeRules=state.payload.schemaOverrides||{};state.ruleDraft={...state.activeRules};state.visible=new Set(getPreference('credit-card-columns',['code','name','leader','zonal','extra','projection','target','saving','mapping']));state.unit=getPreference('credit-card-unit','lac');$('unit').value=state.unit;$('auto-snapshot').checked=getPreference('credit-card-auto-snapshot',false);
  const config=window.ShwapnoDrive.getConfig();$('client-id').value=config.clientId;$('api-key').value=config.apiKey;$('app-id').value=config.appId;
  render();await doRefresh();setInterval(poll,1000);setInterval(autoSnapshot,30000);autoSnapshot();
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){poll();renderConnection();}});
}catch(e){banner(e.message);$('period').textContent='Data unavailable';$('source-badge').textContent='Setup required';}}
init();
